# Generated by Django 4.0.5 on 2022-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
        migrations.AlterField(
            model_name='user',
            name='send_messages',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления?'),
        ),
    ]
